// src/lib/components/FileMenu.svelte
<script lang="ts">
	import { createDropdownMenu, melt } from '@melt-ui/svelte';
	import { Plus, Download, Files, Cog } from 'lucide-svelte';
	const {
		elements: { menu, item, trigger }
	} = createDropdownMenu({
		positioning: {
			placement: 'bottom-start',
			gutter: 0
		}
	});

	const { onDownloadFile, onOpenSettings } = $props();

	const buttons = [
		[Plus, 'New File', '/new', null],
		[Download, 'Download File', null, onDownloadFile],
		[Files, 'Clone File', `${window.location.href}/copy`, null],
		[Cog, 'Settings', null, onOpenSettings]
	];
</script>

<button
	use:melt={$trigger}
	class="relative inline-flex cursor-pointer items-center px-4 py-2 text-sm font-medium text-gray-800 shadow-sm hover:bg-neutral-200 focus:bg-neutral-200 focus:outline-none dark:text-gray-200 dark:hover:bg-neutral-800 dark:focus:bg-neutral-800"
>
	File
	<!-- Chevron Down Icon -->
	<svg
		xmlns="http://www.w3.org/2000/svg"
		viewBox="0 0 20 20"
		fill="currentColor"
		aria-hidden="true"
		class="-mr-1 ml-2 h-5 w-5"
	>
		<path
			fill-rule="evenodd"
			d="M5.22 8.22a.75.75 0 0 1 1.06 0L10 11.94l3.72-3.72a.75.75 0 1 1 1.06 1.06l-4.25 4.25a.75.75 0 0 1-1.06 0L5.22 9.28a.75.75 0 0 1 0-1.06Z"
			clip-rule="evenodd"
		/>
	</svg>
</button>
<!-- menu options -->
<div
	class="ring-opacity-5 w-56 bg-neutral-200 py-1 shadow-lg focus:outline-none dark:bg-neutral-800"
	use:melt={$menu}
>
	{#each buttons as [Icon, text, href, onclick] (text)}
		<a
			use:melt={$item}
			{href}
			{onclick}
			target="_blank"
			class="group flex w-full cursor-pointer items-center px-4 py-2
		text-sm text-gray-800 focus:outline-none data-[highlighted]:bg-neutral-300
		data-[highlighted]:text-gray-900 dark:bg-neutral-800 dark:text-gray-200 dark:data-[highlighted]:bg-neutral-700 dark:data-[highlighted]:text-gray-100"
		>
			<Icon
				class="mr-3 h-5 w-5 text-gray-400 group-hover:text-gray-500 dark:group-hover:text-gray-300"
			/>
			{text}
		</a>
	{/each}
</div>

// components/NavBar/FileMenu.tsx
import { Menu, Transition } from '@headlessui/react';
import {
  ChevronDownIcon,
  CogIcon,
  DownloadIcon,
  PlusIcon,
  TemplateIcon,
} from '@heroicons/react/solid';
import React, { Fragment } from 'react';
import classNames from 'classnames';

export interface FileMenuProps {
  onDownloadFile: () => void;
  onInsertFileTemplate: () => void;
  onOpenSettings: () => void;
}

export const FileMenu = (props: FileMenuProps) => {
  return (
    <Menu as="div" className="relative inline-block text-left">
      {({ open }) => (
        <>
          <div>
            <Menu.Button className="relative inline-flex items-center px-4 py-2 shadow-sm text-sm font-medium text-gray-200 hover:bg-gray-800 focus:bg-gray-800 focus:outline-none">
              File
              <ChevronDownIcon
                className="-mr-1 ml-2 h-5 w-5"
                aria-hidden="true"
              />
            </Menu.Button>
          </div>

          <Transition
            show={open}
            as={Fragment}
            enter="transition ease-out duration-100"
            enterFrom="transform opacity-0 scale-95"
            enterTo="transform opacity-100 scale-100"
            leave="transition ease-in duration-75"
            leaveFrom="transform opacity-100 scale-100"
            leaveTo="transform opacity-0 scale-95"
          >
            <Menu.Items
              static
              className="origin-top-left absolute z-10 left-0 w-56 shadow-lg bg-gray-800 ring-1 ring-black ring-opacity-5 focus:outline-none"
            >
              <div className="py-1">
                <Menu.Item>
                  {({ active }) => (
                    <a
                      href="/"
                      target="_blank"
                      className={classNames(
                        active ? 'bg-gray-700 text-gray-100' : 'text-gray-200',
                        'group flex items-center px-4 py-2 text-sm'
                      )}
                    >
                      <PlusIcon
                        className="mr-3 h-5 w-5 text-gray-400 group-hover:text-gray-300"
                        aria-hidden="true"
                      />
                      New File
                    </a>
                  )}
                </Menu.Item>
                <Menu.Item>
                  {({ active }) => (
                    <button
                      type="button"
                      className={classNames(
                        active ? 'bg-gray-700 text-gray-100' : 'text-gray-200',
                        'group flex items-center px-4 py-2 text-sm w-full focus:outline-none'
                      )}
                      onClick={() => props.onDownloadFile()}
                    >
                      <DownloadIcon
                        className="mr-3 h-5 w-5 text-gray-400 group-hover:text-gray-300"
                        aria-hidden="true"
                      />
                      Download File
                    </button>
                  )}
                </Menu.Item>
                <Menu.Item>
                  {({ active }) => (
                    <button
                      type="button"
                      className={classNames(
                        active ? 'bg-gray-700 text-gray-100' : 'text-gray-200',
                        'group flex items-center px-4 py-2 text-sm w-full focus:outline-none'
                      )}
                      onClick={() => props.onInsertFileTemplate()}
                    >
                      <TemplateIcon
                        className="mr-3 h-5 w-5 text-gray-400 group-hover:text-gray-300"
                        aria-hidden="true"
                      />
                      Insert File Template
                    </button>
                  )}
                </Menu.Item>
                <Menu.Item>
                  {({ active }) => (
                    <button
                      type="button"
                      className={classNames(
                        active ? 'bg-gray-700 text-gray-100' : 'text-gray-200',
                        'group flex items-center px-4 py-2 text-sm w-full focus:outline-none'
                      )}
                      onClick={() => props.onOpenSettings()}
                    >
                      <CogIcon
                        className="mr-3 h-5 w-5 text-gray-400 group-hover:text-gray-300"
                        aria-hidden="true"
                      />
                      Settings
                    </button>
                  )}
                </Menu.Item>
              </div>
            </Menu.Items>
          </Transition>
        </>
      )}
    </Menu>
  );
};
