// src/routes/new/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import RadioGroup from '$lib/components/RadioGroup.svelte';
	import { authState, database } from '$lib/firebase/firebase.svelte';
	import { LANGUAGES, type Language } from '$lib/types';
	import { get, ref, update } from 'firebase/database';
	import generateRandomFileName from './generateRandomFileName';

	let { form } = $props();

	let lang: Language = $state('cpp');
	let compilerOptions: string = $state('');
	let defaultPermission: 'READ_WRITE' | 'READ' | 'PRIVATE' = $state('READ_WRITE');
	let creating = $state(false);

	const DEFAULT_COMPILER_OPTIONS = {
		cpp: '-std=c++23 -O2 -Wall -Wextra -Wshadow -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op',
		java: '',
		py: ''
	};

	$effect(() => {
		compilerOptions = DEFAULT_COMPILER_OPTIONS[lang];
	});

	let userID = $state('');
	let username = $state('');

	$effect(() => {
		if (!authState.firebaseUser) return;

		userID = authState.firebaseUser.uid;
		username = authState.firebaseUser.displayName ?? 'Unnamed User';
		
		const userDataRef = ref(database, `users/${authState.firebaseUser.uid}/data`);
		let isAlive = true;
		get(userDataRef).then((snapshot) => {
			if (!isAlive) return;
			const data = snapshot.val();
			if (data) {
				if (data.defaultPermission === 'READ_WRITE' || data.defaultPermission === 'READ' || data.defaultPermission === 'PRIVATE') {
					defaultPermission = data.defaultPermission;
				}
				if (data.defaultLanguage === 'cpp' || data.defaultLanguage === 'java' || data.defaultLanguage === 'py') {
					lang = data.defaultLanguage;
				}
			}
		});

		return () => isAlive = false;
	});
</script>

<svelte:head>
	<title>Create New File · Real-Time Collaborative Online IDE</title>
	<meta name="robots" content="noindex,nofollow" />
</svelte:head>

<div class="mx-auto flex min-h-full max-w-6xl flex-col p-4 sm:p-6 md:p-8 lg:p-12">
	<form
		class="space-y-6 sm:space-y-8"
		method="POST"
		use:enhance={() => {
			creating = true;

			return async ({ update: submitRequest }) => {
				const userDataRef = ref(database, `users/${authState.firebaseUser!.uid}/data`);
				await update(userDataRef, {
					defaultPermission,
					language: lang
				});
				await submitRequest();
				creating = false;
			};
		}}
	>
		<h1 class="font-semibold text-white md:text-xl xl:text-2xl">Create New File</h1>

		{#if form?.error}
			<p class="text-red-300">Error: {form.error}</p>
		{/if}

		<input name="firebaseUserID" type="hidden" value={userID} />
		<input name="username" type="hidden" value={username} />

		<div class="space-y-4 sm:space-y-6">
			<div>
				<label for="filename" class="block text-sm leading-6 font-medium text-neutral-100">
					File Name
				</label>
				<div class="mt-2">
					<input
						type="text"
						name="filename"
						id="filename"
						class="block w-full max-w-md rounded-md border-0 bg-neutral-900 py-1.5 text-neutral-100 ring-1 shadow-sm ring-neutral-700 ring-inset placeholder:text-neutral-500 focus-visible:ring-2 focus-visible:ring-indigo-700 focus-visible:ring-inset sm:text-sm sm:leading-6"
						defaultValue={generateRandomFileName()}
					/>
				</div>
			</div>

			<div class="mb-6">
				<div class="mb-2 font-medium text-white">Default Sharing Permissions</div>
				<RadioGroup
					name="defaultPermission"
					bind:value={defaultPermission}
					options={{
						READ_WRITE: 'Public Read & Write',
						READ: 'Public View Only',
						PRIVATE: 'Private'
					}}
				></RadioGroup>
			</div>

			<!-- Language Selection -->
			<div class="mb-6">
				<span class="block text-sm leading-6 font-medium text-neutral-100">Language</span>
				<div class="mt-2 flex space-x-3">
					{#each Object.entries(LANGUAGES) as [option, label]}
						<label
							class={'cursor-pointer focus-visible:outline-none ' +
								(lang === option
									? 'bg-indigo-800 text-white hover:bg-indigo-700'
									: 'bg-neutral-900 text-neutral-100 ring-1 ring-neutral-700 ring-inset hover:bg-neutral-800') +
								' flex items-center justify-center rounded-md px-2 py-2 text-sm font-semibold ring-offset-neutral-900 sm:px-4'}
						>
							<input
								type="radio"
								name="language"
								value={option}
								class="sr-only"
								onclick={() => (lang = option)}
								checked={lang === option}
							/>
							{label}
						</label>
					{/each}
				</div>
			</div>

			<div>
				<label for="compilerOptions" class="block text-sm leading-6 font-medium text-neutral-100">
					Compiler Options
				</label>
				<div class="mt-2">
					<input
						type="text"
						name="compilerOptions"
						id="compilerOptions"
						class="block w-full rounded-md border-0 bg-neutral-900 py-1.5 font-mono text-neutral-100 ring-1 shadow-sm ring-neutral-700 ring-inset placeholder:text-neutral-500 focus-visible:ring-2 focus-visible:ring-indigo-700 focus-visible:ring-inset sm:text-sm sm:leading-6"
						value={compilerOptions}
						oninput={(e) => (compilerOptions = (e.target as HTMLInputElement).value)}
					/>
				</div>
			</div>
		</div>

		<div class="space-x-4">
			<button
				type="submit"
				class="rounded-md bg-indigo-700 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-600 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
				disabled={creating}
			>
				{creating ? 'Creating...' : 'Create File'}
			</button>
			<a
				href="/"
				class="focus-visible:outline-offset-neutral-900 rounded-md bg-white/5 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-white/10 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-neutral-700"
			>
				Cancel
			</a>
		</div>
	</form>
</div>

// pages/new.tsx
import { useAtomValue } from 'jotai/utils';
import { useRouter } from 'next/router';
import React, { useEffect, useRef } from 'react';
import invariant from 'tiny-invariant';
import { MessagePage } from '../src/components/MessagePage';
import { LANGUAGES, useNullableUserContext } from '../src/context/UserContext';

import { useState } from 'react';
import { RadioGroup } from '@headlessui/react';
import { Language } from '../src/context/EditorContext';
import Link from 'next/link';
import firebase from 'firebase/app';
import { SharingPermissions } from '../src/components/SharingPermissions';

function classNames(...classes: any[]) {
  return classes.filter(Boolean).join(' ');
}

export const DEFAULT_COMPILER_OPTIONS = {
  cpp: '-std=c++17 -O2 -Wall -Wextra -Wshadow -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op',
  java: '',
  py: '',
};

export default function NewFilePage() {
  const { userData, firebaseUser } = useNullableUserContext();
  const router = useRouter();
  const [lang, setLang] = useState<Language>('cpp');
  const [fileName, setFileName] = useState('');
  const [defaultPerimssion, setDefaultPermission] = useState<
    'READ_WRITE' | 'READ' | 'PRIVATE' | null
  >(null);
  const [compilerOptions, setCompilerOptions] = useState('');

  const isPageLoading = !router.isReady || !userData || !firebaseUser;

  useEffect(() => {
    setCompilerOptions(DEFAULT_COMPILER_OPTIONS[lang]);
  }, [lang]);

  useEffect(() => {
    if (!isPageLoading) {
      setLang(userData.defaultLanguage);
      setDefaultPermission(userData.defaultPermission);
    }
  }, [isPageLoading]);

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (isPageLoading) {
      alert('Page is still loading, please try again later');
      return;
    }
    if (!fileName) {
      alert('Please enter a file name.');
      return;
    }
    (async () => {
      firebase.database().ref(`users/${firebaseUser.uid}/data`).update({
        defaultLanguage: lang,
        defaultPermission: defaultPerimssion,
      });
      const resp = await fetch(`/api/createNewFile`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          workspaceName: fileName,
          userID: firebaseUser.uid,
          userName: firebaseUser.displayName,
          defaultPermission: defaultPerimssion,
          language: lang,
          compilerOptions: {
            ...DEFAULT_COMPILER_OPTIONS,
            [lang]: compilerOptions,
          },
        }),
      });
      const data = await resp.json();
      if (resp.ok) {
        router.push(`/${data.fileID.substring(1)}`);
      } else {
        alert('Error: ' + data.message);
      }
    })();
  };

  return (
    <div className="p-4 sm:p-6 md:p-8 lg:p-12 min-h-full flex flex-col max-w-6xl mx-auto">
      <form className="space-y-6 sm:space-y-8" onSubmit={handleSubmit}>
        <h1 className="text-white font-semibold md:text-xl xl:text-2xl">
          Create New File
        </h1>

        <div className="space-y-4 sm:space-y-6">
          <div>
            <label
              htmlFor="filename"
              className="block text-sm font-medium leading-6 text-gray-100"
            >
              File Name
            </label>
            <div className="mt-2">
              <input
                type="text"
                name="filename"
                id="filename"
                value={fileName}
                onChange={e => setFileName(e.target.value)}
                className="block w-full max-w-md rounded-md border-0 py-1.5 bg-gray-900 text-gray-100 shadow-sm ring-1 ring-inset ring-gray-700 placeholder:text-gray-500 focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-indigo-700 sm:text-sm sm:leading-6"
              />
            </div>
          </div>
          <div className="mb-4">
            <SharingPermissions
              value={defaultPerimssion}
              onChange={setDefaultPermission}
              isOwner={true}
              lightMode
            />
          </div>
          <div>
            <span className="block text-sm font-medium leading-6 text-gray-100">
              Language
            </span>
            <RadioGroup value={lang} onChange={setLang} className="mt-2">
              <RadioGroup.Label className="sr-only">
                {' '}
                Choose a memory option{' '}
              </RadioGroup.Label>
              <div className="flex space-x-3">
                {LANGUAGES.map(option => (
                  <RadioGroup.Option
                    key={option.value}
                    value={option.value}
                    className={({ active, checked }) =>
                      classNames(
                        'cursor-pointer focus-visible:outline-none',
                        active
                          ? 'focus-visible:ring-2 focus-visible:ring-indigo-800 focus-visible:ring-offset-2'
                          : '',
                        checked
                          ? 'bg-indigo-800 text-white hover:bg-indigo-700'
                          : 'ring-1 ring-inset ring-gray-700 bg-gray-900 text-gray-100 hover:bg-gray-800',
                        'flex items-center justify-center rounded-md py-2 px-2 text-sm font-semibold sm:px-4 ring-offset-gray-900'
                      )
                    }
                  >
                    <RadioGroup.Label as="span">
                      {option.label}
                    </RadioGroup.Label>
                  </RadioGroup.Option>
                ))}
              </div>
            </RadioGroup>
          </div>
          <div>
            <label
              htmlFor="compilerOptions"
              className="block text-sm font-medium leading-6 text-gray-100"
            >
              Compiler Options
            </label>
            <div className="mt-2">
              <input
                type="text"
                name="compilerOptions"
                id="compilerOptions"
                value={compilerOptions}
                onChange={e => setCompilerOptions(e.target.value)}
                className="block w-full rounded-md border-0 py-1.5 bg-gray-900 text-gray-100 shadow-sm ring-1 ring-inset ring-gray-700 placeholder:text-gray-500 focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-indigo-700 sm:text-sm sm:leading-6 font-mono"
              />
            </div>
          </div>
        </div>

        <div className="space-x-4">
          <button
            type="submit"
            disabled={isPageLoading}
            className="rounded-md bg-indigo-700 py-2.5 px-3.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
          >
            Create File
          </button>
          <Link href="/">
            <a className="rounded-md bg-white/5 py-2.5 px-3.5 text-sm font-semibold text-white shadow-sm hover:bg-white/10 focus-visible:outline-offset-gray-900 focus-visible:outline-2 focus-visible:outline focus-visible:outline-offset-2 focus-visible:outline-gray-700">
              Cancel
            </a>
          </Link>
        </div>
      </form>
    </div>
  );
}
