// src/components/RealtimeEditor.tsx
import React, { useState, useEffect, useMemo } from 'react';
import { useAtom } from 'jotai';
import { loadingAtom } from '../atoms/workspace';
import LazyMonacoEditor from './MonacoEditor/LazyMonacoEditor';
import { EditorProps } from './MonacoEditor/monaco-editor-types';
import type * as monaco from 'monaco-editor';
import * as Y from 'yjs';
import { WebsocketProvider } from 'y-websocket';
import { MonacoBinding } from 'y-monaco';
import '../styles/yjs.css';
import EditorConnectionStatusIndicator from './editor/EditorConnectionStatusIndicator';
import colorFromUserId, { bgColorFromUserId } from '../scripts/colorFromUserId';
import { useUserContext } from '../context/UserContext';

export interface RealtimeEditorProps extends EditorProps {
  yjsDocumentId: string;
  useEditorWithVim?: boolean;
  dataTestId?: string;
}

const WEBSOCKET_SERVER =
  process.env.NODE_ENV === 'development' || process.env.IS_TEST_ENV
    ? 'ws://localhost:1234'
    : 'wss://yjs.usaco.guide:443';

const RealtimeEditor = ({
  onMount,
  defaultValue,
  yjsDocumentId,
  useEditorWithVim = false,
  dataTestId = '',
  ...props
}: RealtimeEditorProps): JSX.Element => {
  const [editor, setEditor] =
    useState<monaco.editor.IStandaloneCodeEditor | null>(null);
  const { userData, firebaseUser } = useUserContext();
  const [, setLoading] = useAtom(loadingAtom);
  const { editorMode: mode } = userData;

  const [connectionStatus, setConnectionStatus] = useState<
    'disconnected' | 'connecting' | 'connected'
  >('disconnected');
  const [isSynced, setIsSynced] = useState<boolean>(false);

  useEffect(() => {
    if (!editor || !firebaseUser) return;

    const { path } = props;
    const affectsLoading =
      path && ['myfile.cpp', 'myfile.java', 'myfile.py'].includes(path);
    if (affectsLoading) setLoading(true);

    const documentId = yjsDocumentId;

    const ydocument = new Y.Doc();
    const provider = new WebsocketProvider(
      WEBSOCKET_SERVER,
      documentId,
      ydocument
    );

    // Set the cursor color
    // Note that this is actually stored in firebase, but for now we'll just use this
    provider.awareness.setLocalStateField('firebaseUserID', firebaseUser.uid);

    // Bind Yjs to the editor model
    const monacoText = ydocument.getText('monaco');
    const monacoBinding = new MonacoBinding(
      monacoText,
      editor.getModel()!,
      new Set([editor]),
      provider.awareness
    );

    // add custom color for every selector
    provider.awareness.on(
      'change',
      ({
        added,
        updated,
        removed,
      }: {
        added: Array<number>;
        updated: Array<number>;
        removed: Array<number>;
      }) => {
        // We should be responsible and remove styles when someone leaves (ie. removed.length > 0)
        // but I'm lazy...
        if (added.length === 0) return;
        type UserAwarenessData = Map<
          number,
          {
            firebaseUserID: string;
            selection: any;
          }
        >;
        let awarenessState =
          provider.awareness.getStates() as UserAwarenessData;
        for (let addedUserID of added) {
          const firebaseUserID =
            awarenessState.get(addedUserID)?.firebaseUserID ??
            '-NPeGgrWL0zpVHHZ2aECh';
          const styleToAdd = `.yRemoteSelection-${addedUserID}, .yRemoteSelectionHead-${addedUserID} {
              --yjs-selection-color-bg: ${bgColorFromUserId(firebaseUserID)};
              --yjs-selection-color: ${colorFromUserId(firebaseUserID)};
            }`;
          document.body.insertAdjacentHTML(
            'beforeend',
            `<style>${styleToAdd}</style>`
          );
        }
      }
    );

    provider.on(
      'status',
      ({ status }: { status: 'disconnected' | 'connecting' | 'connected' }) => {
        setConnectionStatus(status);
      }
    );
    provider.on('sync', (isSynced: boolean) => {
      if (isSynced) {
        // Check if file needs to be initialized
        const isInitializedMap = ydocument.getMap('isInitialized');
        if (!isInitializedMap.get('isInitialized')) {
          isInitializedMap.set('isInitialized', true);
          monacoText.insert(0, defaultValue ?? '');
        }
      }
      setIsSynced(isSynced);
      setLoading(false);
    });

    return () => {
      setConnectionStatus('disconnected');
      setIsSynced(false);
      // No need to destroy monacoBinding -- it is auto destroyed
      // when monaco unmounts.
      // monacoBinding.destroy();
      ydocument.destroy();
      provider.destroy();
    };
    // defaultValue shouldn't change without the other values changing (and if it does, it's probably a bug)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [yjsDocumentId, firebaseUser, editor, props.path]);

  // make editor read only until yjs syncs with server
  const editorOptions = useMemo(() => {
    let editorOptions = { ...(props.options || {}) };
    if (!isSynced) editorOptions.readOnly = true;
    return editorOptions;
  }, [isSynced, props.options]);

  return (
    <div
      className="tw-forms-disable tw-forms-disable-all-descendants h-full relative"
      data-test-id={dataTestId}
    >
      <EditorConnectionStatusIndicator
        connectionStatus={connectionStatus}
        isSynced={isSynced}
      />
      <LazyMonacoEditor
        {...props}
        options={editorOptions}
        onMount={(e, m) => {
          setEditor(e);
          if (onMount) onMount(e, m);
        }}
        vim={useEditorWithVim && mode === 'Vim'}
      />
    </div>
  );
};

export default RealtimeEditor;

// src/lib/components/editor/RealtimeEditor.svelte
<script lang="ts" module>
	import * as Y from 'yjs';
	import * as awarenessProtocol from 'y-protocols/awareness';

	export type YjsInfo = {
		text: Y.Text;
		awareness: awarenessProtocol.Awareness;
	};

	/**
	 * Props that both the Monaco editor and the Codemirror editor should accept.
	 */
	export type EditorProps = {
		theme?: 'dark' | 'light';
		language?: 'cpp' | 'java' | 'py' | 'plaintext';
		// Optional compiler options for the LSP
		compilerOptions?: string;
		readOnly?: boolean;
		value?: string;

		/**
		 * If provided, connect this editor to YJS.
		 */
		yjsInfo?: YjsInfo;
	};

	const createWebsocketInterceptorClass = (
		onMessageSyncHandler: () => void,
		onSaveHandler: () => void
	) => {
		return class WebsocketInterceptor extends WebSocket {
			send(data: string | ArrayBuffer | Blob | ArrayBufferView) {
				const messageSync = 0; // defined in y-websocket
				if (data instanceof Uint8Array && data.length > 0 && data[0] === messageSync) {
					onMessageSyncHandler();
				}
				super.send(data);
			}

			set onmessage(f: any) {
				const messageSaved = 100; // defined in ide-yjs
				super.onmessage = (m) => {
					const decoder = new Uint8Array(m.data);
					if (decoder.length > 0 && decoder[0] === messageSaved) {
						onSaveHandler();
					} else {
						f(m);
					}
				};
			}
		};
	};
</script>

<script lang="ts">
	import MonacoEditor from './monaco/MonacoEditor.svelte';
	import { WebsocketProvider } from 'y-websocket';
	import { PUBLIC_YJS_SERVER } from '$env/static/public';
	import colorFromUserId, { bgColorFromUserId } from './colorFromUserId';
	import ConnectionStatusIndicator from './ConnectionStatusIndicator.svelte';

	let {
		documentId,
		userId,
		...props
	}: {
		documentId: string;
		/**
		 * Firebase user ID
		 */
		userId: string;
	} & Omit<EditorProps, 'yjsInfo'> = $props();

	let yjsInfo: YjsInfo | undefined = $state(undefined);
	let connectionStatus: 'connecting' | 'saved' | 'saving' = $state('connecting');

	$effect(() => {
		const ydocument = new Y.Doc();

		let lastUpdate = 0;
		const CustomWebsocketInterceptor = createWebsocketInterceptorClass(
			() => {
				if (!provider._synced) {
					return;
				}

				// As a sketchy hack, we'll assume every sync message sent
				// corresponds to an edit the user made.
				lastUpdate = Date.now();
				connectionStatus = 'saving';
			},
			() => {
				if (Date.now() - lastUpdate > 1000) {
					connectionStatus = 'saved';
				}
			}
		);

		const provider = new WebsocketProvider(PUBLIC_YJS_SERVER, documentId, ydocument, {
			WebSocketPolyfill: CustomWebsocketInterceptor
		});

		// Used to compute the cursor color
		provider.awareness.setLocalStateField('firebaseUserID', userId);

		// Bind Yjs to the editor model
		const monacoText = ydocument.getText('monaco');
		yjsInfo = {
			text: monacoText,
			awareness: provider.awareness
		};

		// add custom color for every selector
		provider.awareness.on(
			'change',
			({
				added,
				updated,
				removed
			}: {
				added: Array<number>;
				updated: Array<number>;
				removed: Array<number>;
			}) => {
				// TODO: remove styles when someone leaves (ie. removed.length > 0)
				if (added.length === 0) return;
				type UserAwarenessData = Map<
					number,
					{
						firebaseUserID?: string;
						selection: any;
					}
				>;
				let awarenessState = provider.awareness.getStates() as UserAwarenessData;
				for (let addedUserID of added) {
					let firebaseUserID =
						awarenessState.get(addedUserID)?.firebaseUserID ?? '-NPeGgrWL0zpVHHZ2aECh';
					const styleToAdd = `.yRemoteSelection-${addedUserID}, .yRemoteSelectionHead-${addedUserID} {
	            --yjs-selection-color-bg: ${bgColorFromUserId(firebaseUserID)};
	            --yjs-selection-color: ${colorFromUserId(firebaseUserID)};
	          }`;
					document.body.insertAdjacentHTML('beforeend', `<style>${styleToAdd}</style>`);
				}
			}
		);

		provider.on('status', ({ status }: { status: 'disconnected' | 'connecting' | 'connected' }) => {
			connectionStatus =
				status === 'connected' ? 'saved' : status === 'disconnected' ? 'connecting' : status;
		});

		return () => {
			connectionStatus = 'connecting';
			yjsInfo = undefined;
			ydocument.destroy();
			provider.destroy();
		};
	});

	let editor: MonacoEditor | undefined = $state(undefined);
	export const getValue = () => {
		return editor?.getValue();
	};

	let isSynced = $derived(connectionStatus !== 'connecting');
</script>

<div class="tw-forms-disable tw-forms-disable-all-descendants relative h-full">
	<ConnectionStatusIndicator {connectionStatus} />
	<MonacoEditor bind:this={editor} {yjsInfo} {...props} readOnly={isSynced ? props.readOnly : true}
	></MonacoEditor>
</div>
